version: '3.8'

services:
  # API (NestJS)
  api:
    container_name: api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydatabase
    networks:
      - app-network

  # Frontend (Next.js)
  web:
    container_name: web
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - api
    networks:
      - app-network

  # PostgreSQL
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge 